name: youtube_music_clone
description: A YouTube Music home screen UI clone built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/covers/

  fonts:
    - family: YoutubeSansDark
      fonts:
        - asset: assets/fonts/YouTubeSansDarkRegular.otf
    - family: YoutubeSansSemibold
      fonts:
        - asset: assets/fonts/YouTubeSansSemibold.otf
    - family: YoutubeSansLight
      fonts:
        - asset: assets/fonts/YouTubeSansLight.otf
    - family: YoutubeSansRegular
      fonts:
        - asset: assets/fonts/YouTubeSansRegular.otf
    - family: YoutubeSansDarkMedium
      fonts:
        - asset: assets/fonts/YouTubeSansDarkMedium.otf
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
